# Dockerfile para desarrollo con hot-reload
FROM node:20-alpine
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm ci --legacy-peer-deps

# Copiar el código fuente
COPY . .

# Exponer puerto para desarrollo
EXPOSE 4200

# Iniciar servidor de desarrollo
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
